import { defineConfig } from 'tsup'

export default defineConfig({
  entry: [
    // Main entry
    'src/index.ts',
    // Providers
    'src/providers/index.ts',
    // Hooks
    'src/hooks/index.ts',
    // i18n
    'src/i18n/index.ts',
    // Primitives
    'src/primitives/index.ts',
    // Navigation
    'src/components/navigation/index.ts',
    // UI Components
    'src/components/ui/accordion.tsx',
    'src/components/ui/alert.tsx',
    'src/components/ui/artwork.tsx',
    'src/components/ui/avatar.tsx',
    'src/components/ui/badge.tsx',
    'src/components/ui/pictograms.ts',
    'src/components/ui/box.tsx',
    'src/components/ui/breadcrumb.tsx',
    'src/components/ui/button.tsx',
    'src/components/ui/button-group.tsx',
    'src/components/ui/calendar.tsx',
    'src/components/ui/callout.tsx',
    'src/components/ui/card.tsx',
    'src/components/ui/checkbox.tsx',
    'src/components/ui/code.tsx',
    'src/components/ui/command.tsx',
    'src/components/ui/consent.tsx',
    'src/components/ui/container.tsx',
    'src/components/ui/data-list.tsx',
    'src/components/ui/dropdown-menu.tsx',
    'src/components/ui/flex.tsx',
    'src/components/ui/follow.tsx',
    'src/components/ui/grid.tsx',
    'src/components/ui/heading.tsx',
    'src/components/ui/highlight.tsx',
    'src/components/ui/hover-card.tsx',
    'src/components/ui/indicator.tsx',
    'src/components/ui/input.tsx',
    'src/components/ui/input-otp.tsx',
    'src/components/ui/kbd.tsx',
    'src/components/ui/link.tsx',
    'src/components/ui/logo.tsx',
    'src/components/ui/modal.tsx',
    'src/components/ui/notice.tsx',
    'src/components/ui/pagination.tsx',
    'src/components/ui/popover.tsx',
    'src/components/ui/progress.tsx',
    'src/components/ui/quote.tsx',
    'src/components/ui/radio.tsx',
    'src/components/ui/range.tsx',
    'src/components/ui/section.tsx',
    'src/components/ui/select.tsx',
    'src/components/ui/separator.tsx',
    'src/components/ui/sheet.tsx',
    'src/components/ui/skeleton.tsx',
    'src/components/ui/stepper.tsx',
    'src/components/ui/table.tsx',
    'src/components/ui/tabs.tsx',
    'src/components/ui/tag.tsx',
    'src/components/ui/text.tsx',
    'src/components/ui/theme-artwork.tsx',
    'src/components/ui/theme-toggle.tsx',
    'src/components/ui/tile.tsx',
    'src/components/ui/toast.tsx',
    'src/components/ui/toaster.tsx',
    'src/components/ui/toggle.tsx',
    'src/components/ui/tooltip.tsx',
    'src/components/ui/translate.tsx',
    'src/components/ui/upload.tsx',
    'src/components/ui/use-toast.ts',
  ],
  format: ['cjs', 'esm'],
  dts: true,
  clean: false,
  external: [
    'react',
    'react-dom',
    '@radix-ui/react-accordion',
    '@radix-ui/react-checkbox',
    '@radix-ui/react-collapsible',
    '@radix-ui/react-dialog',
    '@radix-ui/react-dropdown-menu',
    '@radix-ui/react-hover-card',
    '@radix-ui/react-navigation-menu',
    '@radix-ui/react-popover',
    '@radix-ui/react-progress',
    '@radix-ui/react-radio-group',
    '@radix-ui/react-select',
    '@radix-ui/react-separator',
    '@radix-ui/react-slider',
    '@radix-ui/react-slot',
    '@radix-ui/react-switch',
    '@radix-ui/react-tabs',
    '@radix-ui/react-toggle-group',
    '@radix-ui/react-tooltip',
    'cmdk',
    'date-fns',
    'input-otp',
    'react-day-picker',
    'sonner',
  ],
  treeshake: true,
})
